### ISSUE TITLE
Handle Large Numbers

### ISSUE THREAD

**Issue by andrewthad** [andrewthad/scientific-notation#1]
This currently fails on large numbers. This is not difficult to fix, just a little tedious.

**Comment by chessai** [comment]
get good

**Comment by andrewthad** [comment]
This was resolved by 9db88e902a10479520f174f558ecff81f767b4c3. I need to get the newest `bytesmith` on hackage so that I can release `scientific-notation`, but there is some renaming I need to do over there first.
